= Bratu's problem
:icons: font
:stem: latexmath

== Nonlinear equation

Consider the Bratu's problem

[stem]
++++
\begin{cases}
- \nabla \cdot (\nabla u ) + \lambda e^{u} = 0 \text{ in } \Omega \quad (1)
\\
u = 0 \text{ on } \partial \Omega
\end{cases}

++++

=== Continue

Multiply (1) by stem:[v] chosen so that it satisfies the same
boundary conditions as the trial solution stem:[u] and integrate on stem:[\Omega]

[stem]
++++
\displaystyle\int_{\Omega} - \nabla \cdot (\nabla u ) v + \int_{\Omega} \lambda e^{u} v = 0 \quad
\forall v \in H^1_0(\Omega)

++++

By using the formula of Green, we obtain

[stem]
++++
\displaystyle\int_{\Omega}  \nabla u \nabla v - \int_{\partial \Omega} (\nabla u \cdot n ) v + \int_{\Omega} \lambda e^{u} v = 0 \quad
\forall v \in H^1_0(\Omega)

++++

Hence from that stem:[v] is null on the boundary, we have the variational formulation

[stem]
.The variational problem
++++
\text{Determine u } \in H^1_0(\Omega) \text{ satisfying}
\\
\displaystyle\int_{\Omega} \nabla u \nabla v + \int_{\Omega} \lambda e^{u} v = 0 \quad \forall v \in H^1_0(\Omega)
++++

=== Discrete

Conformal approximation:

We use the Galerkin approximation method:

Let stem:[\{ \mathcal{T}_h \}] a family of meshes of stem:[\Omega].

Let stem:[\{ \mathcal{K}, P, \sum \}] a finite Lagrange element of degree stem:[k \geq 1].

Let stem:[P^k_{c,h}] The approximate approximation space defined by

[stem]
++++
P^k_{ c,h} = \{ v \in C^0(\Omega), \forall \mathcal{K} \in \mathcal{T}_h, v|_{\mathcal{K}} \in \mathbb{P}_k(\mathcal{K}) \}

++++

To obtain a conformal approximation, we add the boundary conditions

[stem]
++++
V_h = P^k_{c,h} \cap H^1_0(\Omega)

++++

The problem variable approximation is therefore

[stem]
.Discreet problem
++++
\text{Determine u_h } \in V_h \text{ satisfying}
\\
A(u_h, v_h) = \displaystyle\int_{\Omega_h} \nabla u_h \nabla v_h + \int_{\Omega_h} \lambda e^{u_h} v_h = 0 \quad \forall v_h \in V_h

++++

=== Algebraic:

Let stem:[\{ \varphi_1, \varphi_2, ..., \varphi_N \}] a base of stem:[V_h]. An element stem:[u_h \in V_h] is written as

[stem]
++++
u_h = \sum^{N}_{i=1} u_i \varphi_i
++++

By using stem:[v] as the functions base of stem:[V_h], the problem variable approximation is equivalent to the system

[stem]
.Algebraic problem
++++
\text{Determine } u_i \text{ satisfying}
\\
A(\varphi_i, \varphi_j) = \displaystyle\int_{\Omega_h} \sum_{i=1}^N u_i \nabla \varphi_i \varphi_j
+ \int_{\Omega_h} \lambda e^{\sum_{i=1}^N u_i \varphi_i} \varphi_j = 0 \quad \forall j = 1, \cdots, N

++++

=== Apply Newton-Raphson's method

We can rewrite algebraic problem in the form of system

[stem]
++++
\begin{cases}
A_1(u_1, \cdots , u_N) = \displaystyle\int_{\Omega_h} \sum_{i=1}^N u_i \nabla \varphi_i \varphi_1
+ \int_{\Omega_h} \lambda e^{\sum_{i=1}^N u_i \varphi_i} \varphi_1 = 0
\\
A_2(u_1, \cdots , u_N) = \displaystyle\int_{\Omega_h} \sum_{i=1}^N u_i \nabla \varphi_i \varphi_2
+ \int_{\Omega_h} \lambda e^{\sum_{i=1}^N u_i \varphi_i} \varphi_2 = 0
\\
\vdots
\\
A_N(u_1, \cdots , u_N) = \displaystyle\int_{\Omega_h} \sum_{i=1}^N u_i \nabla \varphi_i \varphi_N
+ \int_{\Omega_h} \lambda e^{\sum_{i=1}^N u_i \varphi_i} \varphi_N = 0
\end{cases}

++++
